app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Auth
//Route::controllers(['auth' => 'Auth\AuthController']);

get('/login/{locale?}',                     ['uses' => 'Auth\AuthController@getLogin',              'as' => 'login']);
post('/login/{locale?}',                    ['uses' => 'Auth\AuthController@postLogin',             'as' => 'postLogin']);

get('/register/{locale?}',                  ['uses' => 'Auth\AuthController@getRegister',           'as' => 'register']);
post('/register/{locale?}',                 ['uses' => 'Auth\AuthController@postRegister',          'as' => 'postRegister']);

get('/logout/{locale?}',                    ['uses' => 'Auth\AuthController@getLogout',             'as' => 'getLogout']);
get('/confirmEmailAddress/{id}/{locale?}',  ['uses' => 'Auth\AuthController@confirmEmailAddress',   'as' => 'confirmEmailAddress']);
get('/auth/confirm/{code}/{locale?}',       ['uses' => 'Auth\AuthController@getConfirm',            'as' => 'getConfirm']);

Route::group(['prefix' => 'insula-actorilor', 'as' => 'insula-actorilor'], function() {
    get('/',                  ['uses' => 'ActorLandController@index']);
    get('/actorul-lunii',     ['uses' => 'ActorLandController@listLunars','as' => '.lunars']);
    get('/filtru',            ['uses' => 'ActorLandController@filterActors', 'as' => '.filter']);
    get('/{slug}',            ['uses' => 'ActorLandController@listActors','as' => '.list']);
});
Route::group(['prefix' => 'actorland', 'as' => 'actorland'], function() {
    get('/',                  ['uses' => 'ActorLandController@index']);
    get('/monthly-actor',             ['uses' => 'ActorLandController@listLunars','as' => '.lunars']);
    get('/filter',            ['uses' => 'ActorLandController@filterActors', 'as' => '.filter']);
    get('/{slug}',            ['uses' => 'ActorLandController@listActors','as' => '.list']);
});

Route::group(['prefix' => 'ambassadors', 'as' => 'ambassadors'], function() {
    get('/',                  ['uses' => 'AmbassadorsController@index']);
});
Route::group(['prefix' => 'ambasadori', 'as' => 'ambasadori'], function() {
    get('/',                  ['uses' => 'AmbassadorsController@index']);
});

// Admin
Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'adminer'], 'namespace' => 'Admin'], function() {
    Route::group(['as' => 'admin.'], function() {
        get('user/needapprove',          ['as' => 'user.needapprove',     'uses' => 'UserController@needApprove']);
        get('user/approve/{id}',         ['as' => 'user.approve',   'uses' => 'UserController@approve']);
        get('user/uncomplete/{id}',      ['as' => 'user.uncomplete',   'uses' => 'UserController@uncomplete']);
        get('employer/needapprove',      ['as' => 'employer.needapprove', 'uses' => 'EmployerController@needApprove']);
        get('actor/needapprove',         ['as' => 'actor.needapprove', 'uses' => 'ActorController@needApprove']);
        get('job/needapprove',           ['as' => 'job.needapprove', 'uses' => 'JobController@needApprove']);
        get('job/approve/{id}',          ['as' => 'job.approve', 'uses' => 'JobController@approve']);
        get('job/uncomplete/{id}',       ['as' => 'job.uncomplete',   'uses' => 'JobController@uncomplete']);
        get('ajaxNewProject/{locale?}',           ['uses' => 'ActorController@ajaxNewProject',  'as' => 'ajaxNewProject']);
        delete('/removeFromPage/{page}',        ['uses' => 'PageController@removeFromPage',         'as' => 'removeFromPage']);

        get('user/create',    ['as' => 'user.create',  'uses' => 'UserController@create']);
        post('user',          ['as' => 'user.store',   'uses' => 'UserController@store']);
        get('user/{username}/edit', ['as' => 'user.edit',    'uses' => 'UserController@edit']);
        patch('user/{id}',    ['as' => 'user.update',  'uses' => 'UserController@update']);
        delete('user/{id}',   ['as' => 'user.destroy', 'uses' => 'UserController@destroy']);
        get('user',           ['as' => 'user.index',   'uses' => 'UserController@index']);

        get('actor/create',             ['as' => 'actor.create',  'uses' => 'ActorController@create']);
        post('actor',                   ['as' => 'actor.store',   'uses' => 'ActorController@store']);
        get('actor/{username}/edit',    ['as' => 'actor.edit',    'uses' => 'ActorController@edit']);
        patch('actor/{username}/edit',  ['as' => 'actor.update',  'uses' => 'ActorController@update']);
        delete('actor/{id}',            ['as' => 'actor.destroy', 'uses' => 'ActorController@destroy']);
        get('actor',                    ['as' => 'actor.index',   'uses' => 'ActorController@index']);

        get('employer/create',             ['as' => 'employer.create',  'uses' => 'EmployerController@create']);
        post('employer',                   ['as' => 'employer.store',   'uses' => 'EmployerController@store']);
        get('employer/{username}/edit',    ['as' => 'employer.edit',    'uses' => 'EmployerController@edit']);
        patch('employer/{username}/edit',  ['as' => 'employer.update',  'uses' => 'EmployerController@update']);
        delete('employer/{id}',            ['as' => 'employer.destroy', 'uses' => 'EmployerController@destroy']);
        get('employer',                    ['as' => 'employer.index',   'uses' => 'EmployerController@index']);

        get('ambassador/create',             ['as' => 'ambassador.create',  'uses' => 'AmbassadorController@create']);
        post('ambassador',                   ['as' => 'ambassador.store',   'uses' => 'AmbassadorController@store']);
        get('ambassador/{username}/edit',    ['as' => 'ambassador.edit',    'uses' => 'AmbassadorController@edit']);
        patch('ambassador/{username}/edit',  ['as' => 'ambassador.update',  'uses' => 'AmbassadorController@update']);
        delete('ambassador/{id}',            ['as' => 'ambassador.destroy', 'uses' => 'AmbassadorController@destroy']);
        get('ambassador',                    ['as' => 'ambassador.index',   'uses' => 'AmbassadorController@index']);

        get('lunar/create',             ['as' => 'lunar.create',  'uses' => 'LunarController@create']);
        post('lunar',                   ['as' => 'lunar.store',   'uses' => 'LunarController@store']);
        get('lunar/{username}/edit',    ['as' => 'lunar.edit',    'uses' => 'LunarController@edit']);
        patch('lunar/{username}/edit',  ['as' => 'lunar.update',  'uses' => 'LunarController@update']);
        delete('lunar/{id}',            ['as' => 'lunar.destroy', 'uses' => 'LunarController@destroy']);
        get('lunar',                    ['as' => 'lunar.index',   'uses' => 'LunarController@index']);

    });
    resource('job',             'JobController');
    resource('page',            'PageController');
    resource('sliders',         'SliderController');
    get('/{locale?}',  ['as' => 'admin.dashboard', 'uses' => 'HomeController@index']);
});

get('/confirmDelete/{code}',                ['uses' => 'ProfileController@confirmDelete',              'as' => 'profile.confirmDelete']);

Route::group(['middleware' => ['auth', 'owner']], function() {

    Route::resource('profile', 'ProfileController', ['except' => ['show', 'destroy', 'store', 'index', 'create', 'edit']]);
    // Ajax
    Route::group(['prefix' => 'profile', 'as' => 'profile.'], function() {
        get('{username}/initiateDelete/{locale?}',              ['uses' => 'ProfileController@initiateDelete',            'as' => 'initiateDelete']);

        patch('{username}/ajaxUpdateUser/{locale?}',            ['uses' => 'ProfileController@ajaxUpdateUser',            'as' => 'ajaxUpdateUser']);
        patch('{username}/ajaxUpdateCompany/{locale?}',         ['uses' => 'ProfileController@ajaxUpdateCompany',         'as' => 'ajaxUpdateCompany']);
        patch('{username}/ajaxUpdateCharacteristics/{locale?}', ['uses' => 'ProfileController@ajaxUpdateCharacteristics', 'as' => 'ajaxUpdateCharacteristics']);

        patch('{username}/ajaxUpdateEducation/{locale?}',       ['uses' => 'ProfileController@ajaxUpdateEducation',       'as' => 'ajaxUpdateEducation']);
        post('{username}/ajaxUpdateFiles/{locale?}',            ['uses' => 'ProfileController@ajaxUpdateFiles',           'as' => 'ajaxUpdateFiles']);
        post('{username}/ajaxComplete/{locale?}',               ['uses' => 'ProfileController@ajaxComplete',              'as' => 'ajaxComplete']);

        get('{username}/ajaxNewProject/{locale?}',              ['uses' => 'ProfileController@ajaxNewProject',            'as' => 'ajaxNewProject']);
        get('{username}/ajaxNewWorkshop/{locale?}',             ['uses' => 'ProfileController@ajaxNewWorkshop',           'as' => 'ajaxNewWorkshop']);
        get('{username}/ajaxNewVimeo/{locale?}',                ['uses' => 'ProfileController@ajaxNewVimeo',              'as' => 'ajaxNewVimeo']);
        delete('{username}/removeFromProfile/{locale?}',        ['uses' => 'ProfileController@removeFromProfile',         'as' => 'removeFromProfile']);

        get('{username}/ajaxShowCharasteristics/{locale?}',     ['uses' => 'ProfileController@ajaxShowCharasteristics',   'as' => 'ajaxShowCharasteristics']);
        get('{username}/ajaxShowEducation/{locale?}',           ['uses' => 'ProfileController@ajaxShowEducation',         'as' => 'ajaxShowEducation']);
        get('{username}/ajaxShowFiles/{locale?}',      ['uses' => 'ProfileController@ajaxShowFiles',             'as' => 'ajaxShowFiles']);

        post('{username}/ajaxShowUser/{locale?}',               ['uses' => 'ProfileController@ajaxShowUser',              'as' => 'ajaxShowUser']);
    });
});

app/Models/Employer.php
<?php

namespace Rcc\Models;

use Illuminate\Database\Eloquent\Model;

class Employer extends Model
{
	protected $fillable = ['logo_id', 'company', 'address', 'post_code', 'website', 'info'];

    public function User()
	{
		return $this->belongsTo('Rcc\Models\User');
	}

	public function EmployerType() {
		return $this->belongsTo('Rcc\Models\EmployerType');
	}

	public function UnapprovedEmployers() {
		return $this->whereHas('user', function($query) {
			$query->whereNotNull('updates');
		})->with('user')->get();
	}

	public function EmployerWithUser($username) {
		return $this->whereHas('user', function($query) use ($username) {
			$query->where('username', $username);
		})->with('user')->first();
	}

}

app/Models/EmployerType.php
<?php

namespace Rcc\Models;

use Illuminate\Database\Eloquent\Model;

class EmployerType extends Model
{
   	public function Employers() {
        return $this->hasMany('Rcc\Models\Employer');
    }
}

app/Http/Controllers/Admin/EmployerController.php
<?php

namespace Rcc\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Rcc\Http\Controllers\Controller;
use Employer;
use Rep;
use User;

class EmployerController extends Controller {

	/**
	 * Create a new controller instance.
	 *
	 * @param User $user
	 * @param Employer $employer
	 * @param Request $request
	 * @internal param Language $language
	 */
	public function __construct(User $user, Employer $employer, Request $request) {
		parent::__construct($request);

		$this->employer = $employer;
		$this->user = $user;
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index() {
		$data['admin_languages'] = $this->data['admin_languages'];
		$data['employers'] = $this->employer->with('user')->get();

		return view('admin.employer.index', $data);
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int $username
	 *
	 * @return Response
	 */
	public function edit($username) {
		$data['admin_languages'] = $this->getAdminLanguages($username);
		$data['employer'] = $this->employer->EmployerWithUser($username);
		$data += Rep::getUserSelects();

		return view('admin.employer.edit', $data);
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int $username
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function update($username, Request $request) {

		$employer = $this->employer->EmployerWithUser($username);

		// Update user
		$employer->user()->update($request->input('user'));
		if(0 === $employer->user->password) {
			Rep::setPassAndSendMail($employer->user);
		}

		// Update employer
		$employer->update($request->except(['_method', '_token', 'user']));

		return back()->with('success_message', trans('messages.user_updated'));
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int $id
	 *
	 * @return Response
	 */
	public function destroy($id) {
		$this->user->destroy($id);

		return back()->with('success_message', trans('messages.user_deleted'));
	}

	/**
	 * Display a listing of non-approved employers.
	 *
	 * @return Response
	 */
	public function needApprove() {
		$data['admin_languages'] = $this->data['admin_languages'];
		$data['employers'] = $this->employer->UnapprovedEmployers();

		return view('admin.employer.index', $data);
	}

}

resources/views/admin/employer/create.blade.php
@extends('admin.layouts.app')

@section('pagehead')
	{{ trans('messages.add_new_employer') }}
@stop

@section('content')
    
{!! Form::open( ['route' => 'admin.employer.store', 'files'=>true]) !!}
   @include('admin.includes.employers.form')
{!! Form::close() !!}

@stop

resources/views/admin/employer/edit.blade.php
@extends('admin.layouts.app')
@section('pagehead')
	{{ trans('messages.edit_employer') }}
	{!! link_to_route('admin.user.create', trans('messages.add_new'), ['locale' => App::getLocale()], ['class' => 'btn bg-purple margin']) !!}
	{!! link_to_route('profile.show', trans('messages.view_profile'), [$employer->user->username, 'locale' => App::getLocale()], ['class' => 'btn bg-green', 'target' => 'blank']) !!}
@stop

@section('content')
    
{!! Form::model( $employer, ['route' => ['admin.employer.update', $employer->user->username, 'locale' => App::getLocale()], 'method' => 'PATCH'] ) !!}
   @include('admin.includes.employers.form')
{!! Form::close() !!}

<div id="mediaContent" class="employerMedia">
	<ul class="nav nav-tabs" role="tablist">
		<li role="presentation">
			<a href="#filestab" id="showMedia" aria-controls="media" role="tab" data-show="{{ route('profile.ajaxShowFiles', [$employer->user->username, App::getLocale()])  }}" data-toggle="tab">{{ trans('messages.media') }}</a>
		</li>
	</ul>
	<div class="tab-content">
	</div>
</div>

@stop

resources/views/admin/employer/index.blade.php
@extends('admin.layouts.app')

@section('pagehead')
    {{ trans('messages.all_employers') }}
    {!! link_to_route('admin.user.create', trans('messages.add_new'), ['locale' => App::getLocale()], ['class' => 'btn bg-purple margin']) !!}
@stop


@section('content')

	<div class="box box-danger">
        <div class="box-header">
          <h3 class="box-title">{{ trans('messages.all_employers') }}</h3>
        </div>
        <div class="box-body">
          	<table id="example1" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th width="50">Employer&nbsp;ID&nbsp;/ User&nbsp;ID</th>
                        <th>{{ trans('messages.the_user') }}</th>
                        <th>{{ trans('messages.company_name') }}</th>
                        <th>{{ trans('messages.address') }}</th>
                        <th>{{ trans('messages.post_code') }}</th>
                        <th>{{ trans('messages.website') }}</th>
                        {{--<th>Logo</th>--}}
                        {{--<th>{{ trans('messages.images') }}</th>--}}
                    </tr>
                </thead>

                <tbody>
                	@foreach ( $employers as $employer )
                        <tr>
                            <td class="text-center">{{ $employer->id }} / {{ $employer->user->id }}</td>
                            <td>
                                <h4 class="numeUser">{!! link_to_route('admin.employer.edit', $employer->user->fname . ' ' . $employer->user->lname, [$employer->user->username,  'locale' => App::getLocale()]) !!}</h4>
                                @include('admin.includes._crud', ['id' => $employer->user->id, 'type' => 'employer', 'username' => $employer->user->username])
                            </td>
                            <td>{{ $employer->company }}</td>
                            <td>{{ $employer->address }}</td>
                            <td>{{ $employer->post_code }}</td>
                            <td><a href="http://{{ $employer->website }}" target="_blank">{{ $employer->website }}</a></td>
                            {{--<td>--}}
                                {{--<img src="{{ $employer->logo }}" width="100" alt="">--}}
                            {{--</td>--}}
                            {{--<td>--}}
                                {{--@if (isset ($employer->user->images[0]))--}}
                                    {{--<img src="{{ $employer->user->images[0]->path }}" width="100" alt="">--}}
                                {{--@endif--}}
                            {{--</td>--}}
                        </tr>
                	@endforeach
                </tbody>

            </table>
        </div> {{-- // box-body --}}
	</div>

@stop