app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Auth
//Route::controllers(['auth' => 'Auth\AuthController']);

get('/login/{locale?}',                     ['uses' => 'Auth\AuthController@getLogin',              'as' => 'login']);
post('/login/{locale?}',                    ['uses' => 'Auth\AuthController@postLogin',             'as' => 'postLogin']);

get('/register/{locale?}',                  ['uses' => 'Auth\AuthController@getRegister',           'as' => 'register']);
post('/register/{locale?}',                 ['uses' => 'Auth\AuthController@postRegister',          'as' => 'postRegister']);

get('/logout/{locale?}',                    ['uses' => 'Auth\AuthController@getLogout',             'as' => 'getLogout']);
get('/confirmEmailAddress/{id}/{locale?}',  ['uses' => 'Auth\AuthController@confirmEmailAddress',   'as' => 'confirmEmailAddress']);
get('/auth/confirm/{code}/{locale?}',       ['uses' => 'Auth\AuthController@getConfirm',            'as' => 'getConfirm']);

Route::group(['prefix' => 'insula-actorilor', 'as' => 'insula-actorilor'], function() {
    get('/',                  ['uses' => 'ActorLandController@index']);
    get('/actorul-lunii',     ['uses' => 'ActorLandController@listLunars','as' => '.lunars']);
    get('/filtru',            ['uses' => 'ActorLandController@filterActors', 'as' => '.filter']);
    get('/{slug}',            ['uses' => 'ActorLandController@listActors','as' => '.list']);
});
Route::group(['prefix' => 'actorland', 'as' => 'actorland'], function() {
    get('/',                  ['uses' => 'ActorLandController@index']);
    get('/monthly-actor',             ['uses' => 'ActorLandController@listLunars','as' => '.lunars']);
    get('/filter',            ['uses' => 'ActorLandController@filterActors', 'as' => '.filter']);
    get('/{slug}',            ['uses' => 'ActorLandController@listActors','as' => '.list']);
});

Route::group(['prefix' => 'ambassadors', 'as' => 'ambassadors'], function() {
    get('/',                  ['uses' => 'AmbassadorsController@index']);
});
Route::group(['prefix' => 'ambasadori', 'as' => 'ambasadori'], function() {
    get('/',                  ['uses' => 'AmbassadorsController@index']);
});

// Admin
Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'adminer'], 'namespace' => 'Admin'], function() {
    Route::group(['as' => 'admin.'], function() {
        get('user/needapprove',          ['as' => 'user.needapprove',     'uses' => 'UserController@needApprove']);
        get('user/approve/{id}',         ['as' => 'user.approve',   'uses' => 'UserController@approve']);
        get('user/uncomplete/{id}',      ['as' => 'user.uncomplete',   'uses' => 'UserController@uncomplete']);
        get('employer/needapprove',      ['as' => 'employer.needapprove', 'uses' => 'EmployerController@needApprove']);
        get('actor/needapprove',         ['as' => 'actor.needapprove', 'uses' => 'ActorController@needApprove']);
        get('job/needapprove',           ['as' => 'job.needapprove', 'uses' => 'JobController@needApprove']);
        get('job/approve/{id}',          ['as' => 'job.approve', 'uses' => 'JobController@approve']);
        get('job/uncomplete/{id}',       ['as' => 'job.uncomplete',   'uses' => 'JobController@uncomplete']);
        get('ajaxNewProject/{locale?}',           ['uses' => 'ActorController@ajaxNewProject',  'as' => 'ajaxNewProject']);
        delete('/removeFromPage/{page}',        ['uses' => 'PageController@removeFromPage',         'as' => 'removeFromPage']);

        get('user/create',    ['as' => 'user.create',  'uses' => 'UserController@create']);
        post('user',          ['as' => 'user.store',   'uses' => 'UserController@store']);
        get('user/{username}/edit', ['as' => 'user.edit',    'uses' => 'UserController@edit']);
        patch('user/{id}',    ['as' => 'user.update',  'uses' => 'UserController@update']);
        delete('user/{id}',   ['as' => 'user.destroy', 'uses' => 'UserController@destroy']);
        get('user',           ['as' => 'user.index',   'uses' => 'UserController@index']);

        get('actor/create',             ['as' => 'actor.create',  'uses' => 'ActorController@create']);
        post('actor',                   ['as' => 'actor.store',   'uses' => 'ActorController@store']);
        get('actor/{username}/edit',    ['as' => 'actor.edit',    'uses' => 'ActorController@edit']);
        patch('actor/{username}/edit',  ['as' => 'actor.update',  'uses' => 'ActorController@update']);
        delete('actor/{id}',            ['as' => 'actor.destroy', 'uses' => 'ActorController@destroy']);
        get('actor',                    ['as' => 'actor.index',   'uses' => 'ActorController@index']);

        get('employer/create',             ['as' => 'employer.create',  'uses' => 'EmployerController@create']);
        post('employer',                   ['as' => 'employer.store',   'uses' => 'EmployerController@store']);
        get('employer/{username}/edit',    ['as' => 'employer.edit',    'uses' => 'EmployerController@edit']);
        patch('employer/{username}/edit',  ['as' => 'employer.update',  'uses' => 'EmployerController@update']);
        delete('employer/{id}',            ['as' => 'employer.destroy', 'uses' => 'EmployerController@destroy']);
        get('employer',                    ['as' => 'employer.index',   'uses' => 'EmployerController@index']);

        get('ambassador/create',             ['as' => 'ambassador.create',  'uses' => 'AmbassadorController@create']);
        post('ambassador',                   ['as' => 'ambassador.store',   'uses' => 'AmbassadorController@store']);
        get('ambassador/{username}/edit',    ['as' => 'ambassador.edit',    'uses' => 'AmbassadorController@edit']);
        patch('ambassador/{username}/edit',  ['as' => 'ambassador.update',  'uses' => 'AmbassadorController@update']);
        delete('ambassador/{id}',            ['as' => 'ambassador.destroy', 'uses' => 'AmbassadorController@destroy']);
        get('ambassador',                    ['as' => 'ambassador.index',   'uses' => 'AmbassadorController@index']);

        get('lunar/create',             ['as' => 'lunar.create',  'uses' => 'LunarController@create']);
        post('lunar',                   ['as' => 'lunar.store',   'uses' => 'LunarController@store']);
        get('lunar/{username}/edit',    ['as' => 'lunar.edit',    'uses' => 'LunarController@edit']);
        patch('lunar/{username}/edit',  ['as' => 'lunar.update',  'uses' => 'LunarController@update']);
        delete('lunar/{id}',            ['as' => 'lunar.destroy', 'uses' => 'LunarController@destroy']);
        get('lunar',                    ['as' => 'lunar.index',   'uses' => 'LunarController@index']);

    });
    resource('job',             'JobController');
    resource('page',            'PageController');
    resource('sliders',         'SliderController');
    get('/{locale?}',  ['as' => 'admin.dashboard', 'uses' => 'HomeController@index']);
});

get('/confirmDelete/{code}',                ['uses' => 'ProfileController@confirmDelete',              'as' => 'profile.confirmDelete']);

Route::group(['middleware' => ['auth', 'owner']], function() {

    Route::resource('profile', 'ProfileController', ['except' => ['show', 'destroy', 'store', 'index', 'create', 'edit']]);
    // Ajax
    Route::group(['prefix' => 'profile', 'as' => 'profile.'], function() {
        get('{username}/initiateDelete/{locale?}',              ['uses' => 'ProfileController@initiateDelete',            'as' => 'initiateDelete']);

        patch('{username}/ajaxUpdateUser/{locale?}',            ['uses' => 'ProfileController@ajaxUpdateUser',            'as' => 'ajaxUpdateUser']);
        patch('{username}/ajaxUpdateCompany/{locale?}',         ['uses' => 'ProfileController@ajaxUpdateCompany',         'as' => 'ajaxUpdateCompany']);
        patch('{username}/ajaxUpdateCharacteristics/{locale?}', ['uses' => 'ProfileController@ajaxUpdateCharacteristics', 'as' => 'ajaxUpdateCharacteristics']);

        patch('{username}/ajaxUpdateEducation/{locale?}',       ['uses' => 'ProfileController@ajaxUpdateEducation',       'as' => 'ajaxUpdateEducation']);
        post('{username}/ajaxUpdateFiles/{locale?}',            ['uses' => 'ProfileController@ajaxUpdateFiles',           'as' => 'ajaxUpdateFiles']);
        post('{username}/ajaxComplete/{locale?}',               ['uses' => 'ProfileController@ajaxComplete',              'as' => 'ajaxComplete']);

        get('{username}/ajaxNewProject/{locale?}',              ['uses' => 'ProfileController@ajaxNewProject',            'as' => 'ajaxNewProject']);
        get('{username}/ajaxNewWorkshop/{locale?}',             ['uses' => 'ProfileController@ajaxNewWorkshop',           'as' => 'ajaxNewWorkshop']);
        get('{username}/ajaxNewVimeo/{locale?}',                ['uses' => 'ProfileController@ajaxNewVimeo',              'as' => 'ajaxNewVimeo']);
        delete('{username}/removeFromProfile/{locale?}',        ['uses' => 'ProfileController@removeFromProfile',         'as' => 'removeFromProfile']);

        get('{username}/ajaxShowCharasteristics/{locale?}',     ['uses' => 'ProfileController@ajaxShowCharasteristics',   'as' => 'ajaxShowCharasteristics']);
        get('{username}/ajaxShowEducation/{locale?}',           ['uses' => 'ProfileController@ajaxShowEducation',         'as' => 'ajaxShowEducation']);
        get('{username}/ajaxShowFiles/{locale?}',      ['uses' => 'ProfileController@ajaxShowFiles',             'as' => 'ajaxShowFiles']);

        post('{username}/ajaxShowUser/{locale?}',               ['uses' => 'ProfileController@ajaxShowUser',              'as' => 'ajaxShowUser']);
    });
});

app/Http/Controllers/Admin/UserController.php
<?php

namespace Rcc\Http\Controllers\Admin;

use Rcc\Http\Requests;
use Rcc\Http\Controllers\Controller;

use User;
use AddUserRequest;
use EditUserRequest;
use Rep;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     * @return \Illuminate\View\View
     */
    public function index()
    {
        $data['admin_languages'] = $this->data['admin_languages'];
        $data['users'] = User::all();
        return view('admin.user.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     * @return \Illuminate\View\View
     */
    public function create()
    {
        $data = Rep::getUserSelects();
        $data['admin_languages'] = $this->data['admin_languages'];
        return view('admin.user.create', $data);
    }

    /**
     * Show the form for editing the specified resource.
     * @param $username
     * @return \Illuminate\View\View
     * @internal param $id
     */
    public function edit($username)
    {
        $data['admin_languages'] = $this->getAdminLanguages($username);
        $data['user'] = Rep::getUserWithRelations($username);
        $data += Rep::getUserSelects();

        return view('admin.user.edit', $data);
    }

    /**
     * Display a listing of non-approved users.
     * @return \Illuminate\View\View
     */
    public function needApprove()
    {
        $data['admin_languages'] = $this->data['admin_languages'];
        $data['users'] = Rep::getUnApprovedUsers();
        return view('admin.user.index', $data);
    }

    /**
     * Store a newly created resource in storage.
     * @param AddUserRequest $request
     * @return $this|\Illuminate\Http\RedirectResponse
     */
    public function store(AddUserRequest $request)
    {
        $user = Rep::createUserFromRequest($request);

        return redirect()->route('admin.user.edit', [$user->username, 'locale' => $this->locale])->with('success_message', trans('messages.user_created'));
    }

    /**
     * Update the specified resource in storage.
     * @param $id
     * @param EditUserRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update($id, EditUserRequest $request)
    {
        $user = Rep::updateUserFromRequest($id, $request);
        return back()->with('success_message', trans('messages.user_updated'));
    }

    /**
     * Remove the specified resource from storage.
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        User::destroy($id);
        return back()->with('success_message', trans('messages.user_deleted'));
    }

    /**
     * Approve user
     * @param $username
     * @return \Illuminate\Http\RedirectResponse
     */
    public function approve($username)
    {
        Rep::approveUser($username);
        return back()->with('success_message', trans('messages.approved'));
    }

    /**
     * Uncomplete user
     * @param $username
     * @return \Illuminate\Http\RedirectResponse
     */
    public function uncomplete($username)
    {
        Rep::unCompleteProfile($username, $notify = true);
        return back()->with('success_message', trans('messages.unapproved'));
    }

}

resources/views/admin/user/create.blade.php
@extends('admin.layouts.app')

@section('pagehead')
	{{ trans('messages.add_new_user') }}
@stop

@section('content')
    
{!! Form::open( ['route' => ['admin.user.store', 'locale' => App::getLocale()]]) !!}
   @include('admin.includes.users.form')
{!! Form::close() !!}

@stop

resources/views/admin/user/edit.blade.php
@extends('admin.layouts.app')

@section('pagehead')
	{{ trans('messages.edit_user') }}
	{!! link_to_route('admin.user.create', trans('messages.add_new'), ['locale' => App::getLocale()], ['class' => 'btn bg-purple margin']) !!}

	@if ($user->actor)
		{!! link_to_route('admin.actor.edit', trans('messages.edit_actor'), [$user->username, 'locale' => App::getLocale()], ['class' => 'btn bg-orange margin']) !!}
	@elseif ($user->employer)
		{!! link_to_route('admin.employer.edit', trans('messages.edit_employer'), [$user->username, 'locale' => App::getLocale()], ['class' => 'btn bg-orange margin']) !!}
	@endif

	{!! link_to_route('profile.show', trans('messages.view_profile'), [$user->username, 'locale' => App::getLocale()], ['class' => 'btn bg-green margin', 'target' => 'blank']) !!}

@stop

@section('content')
    
{!! Form::model( $user, ['route' => ['admin.user.update', $user->id, 'locale' => App::getLocale()], 'method' => 'PATCH'] ) !!}
   @include('admin.includes.users.form')
{!! Form::close() !!}

@stop

resources/views/admin/user/index.blade.php
@extends('admin.layouts.app')

@section('pagehead')
	{{ trans('messages.all_users') }}
	{!! link_to_route('admin.user.create', trans('messages.add_new'), ['locale' => App::getLocale()], ['class' => 'btn bg-purple margin']) !!}
@stop

@section('content')

	<div class="box box-danger">
        <div class="box-header">
          <h3 class="box-title">{{ trans('messages.all_users') }}</h3>
        </div>
        <div class="box-body">
          	<table id="example1" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th width="25">ID</th>
                        <th>{{ trans('messages.name') }}</th>
                        <th>{{ trans('messages.username') }}</th>
                        <th>{{ trans('messages.kind') }}</th>
                        <th>{{ trans('messages.email') }}</th>
                        <th>{{ trans('messages.mobile') }}</th>
                        <th>{{ trans('messages.country') }}</th>
                        <th>{{ trans('messages.city') }}</th>
                    </tr>
                </thead>

                <tbody>
                	@foreach ( $users as $user )
                        <?php
                            $type = 'special';

                            if ($user->role_id == $talent_role_id)
                                $type = 'actor';
                            else if($user->role_id == $employer_role_id)
                                $type = 'employer';
                        ?>
                        <tr>
                            <td class="text-center">{{ $user->id }}</td>
                            <td>
                                {!! link_to_route('admin.user.edit', $user->fname . ' ' . $user->lname, [$user->username, 'locale' => App::getLocale()]) !!}
                                @include('admin.includes._crud', ['id' => $user->id, 'type' => 'user', 'username' => $user->username])
                            </td>

                            <td>{{ $user->username }}</td>
                            <td>{{ $type }}</td>
                            <td>{{ $user->email }}</td>
                            <td>{{ $user->mobile }}</td>
                            <td>{{ $user->country->name }}</td>
                            <td>{{ $user->city }}</td>
                        </tr>
                	@endforeach
                </tbody>

            </table>
        </div> {{-- // box-body --}}
	</div>

@stop