app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Auth
//Route::controllers(['auth' => 'Auth\AuthController']);

get('/login/{locale?}',                     ['uses' => 'Auth\AuthController@getLogin',              'as' => 'login']);
post('/login/{locale?}',                    ['uses' => 'Auth\AuthController@postLogin',             'as' => 'postLogin']);

get('/register/{locale?}',                  ['uses' => 'Auth\AuthController@getRegister',           'as' => 'register']);
post('/register/{locale?}',                 ['uses' => 'Auth\AuthController@postRegister',          'as' => 'postRegister']);

get('/logout/{locale?}',                    ['uses' => 'Auth\AuthController@getLogout',             'as' => 'getLogout']);
get('/confirmEmailAddress/{id}/{locale?}',  ['uses' => 'Auth\AuthController@confirmEmailAddress',   'as' => 'confirmEmailAddress']);
get('/auth/confirm/{code}/{locale?}',       ['uses' => 'Auth\AuthController@getConfirm',            'as' => 'getConfirm']);

Route::group(['prefix' => 'insula-actorilor', 'as' => 'insula-actorilor'], function() {
    get('/',                  ['uses' => 'ActorLandController@index']);
    get('/actorul-lunii',     ['uses' => 'ActorLandController@listLunars','as' => '.lunars']);
    get('/filtru',            ['uses' => 'ActorLandController@filterActors', 'as' => '.filter']);
    get('/{slug}',            ['uses' => 'ActorLandController@listActors','as' => '.list']);
});
Route::group(['prefix' => 'actorland', 'as' => 'actorland'], function() {
    get('/',                  ['uses' => 'ActorLandController@index']);
    get('/monthly-actor',             ['uses' => 'ActorLandController@listLunars','as' => '.lunars']);
    get('/filter',            ['uses' => 'ActorLandController@filterActors', 'as' => '.filter']);
    get('/{slug}',            ['uses' => 'ActorLandController@listActors','as' => '.list']);
});

Route::group(['prefix' => 'ambassadors', 'as' => 'ambassadors'], function() {
    get('/',                  ['uses' => 'AmbassadorsController@index']);
});
Route::group(['prefix' => 'ambasadori', 'as' => 'ambasadori'], function() {
    get('/',                  ['uses' => 'AmbassadorsController@index']);
});

// Admin
Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'adminer'], 'namespace' => 'Admin'], function() {
    Route::group(['as' => 'admin.'], function() {
        get('user/needapprove',          ['as' => 'user.needapprove',     'uses' => 'UserController@needApprove']);
        get('user/approve/{id}',         ['as' => 'user.approve',   'uses' => 'UserController@approve']);
        get('user/uncomplete/{id}',      ['as' => 'user.uncomplete',   'uses' => 'UserController@uncomplete']);
        get('employer/needapprove',      ['as' => 'employer.needapprove', 'uses' => 'EmployerController@needApprove']);
        get('actor/needapprove',         ['as' => 'actor.needapprove', 'uses' => 'ActorController@needApprove']);
        get('job/needapprove',           ['as' => 'job.needapprove', 'uses' => 'JobController@needApprove']);
        get('job/approve/{id}',          ['as' => 'job.approve', 'uses' => 'JobController@approve']);
        get('job/uncomplete/{id}',       ['as' => 'job.uncomplete',   'uses' => 'JobController@uncomplete']);
        get('ajaxNewProject/{locale?}',           ['uses' => 'ActorController@ajaxNewProject',  'as' => 'ajaxNewProject']);
        delete('/removeFromPage/{page}',        ['uses' => 'PageController@removeFromPage',         'as' => 'removeFromPage']);

        get('user/create',    ['as' => 'user.create',  'uses' => 'UserController@create']);
        post('user',          ['as' => 'user.store',   'uses' => 'UserController@store']);
        get('user/{username}/edit', ['as' => 'user.edit',    'uses' => 'UserController@edit']);
        patch('user/{id}',    ['as' => 'user.update',  'uses' => 'UserController@update']);
        delete('user/{id}',   ['as' => 'user.destroy', 'uses' => 'UserController@destroy']);
        get('user',           ['as' => 'user.index',   'uses' => 'UserController@index']);

        get('actor/create',             ['as' => 'actor.create',  'uses' => 'ActorController@create']);
        post('actor',                   ['as' => 'actor.store',   'uses' => 'ActorController@store']);
        get('actor/{username}/edit',    ['as' => 'actor.edit',    'uses' => 'ActorController@edit']);
        patch('actor/{username}/edit',  ['as' => 'actor.update',  'uses' => 'ActorController@update']);
        delete('actor/{id}',            ['as' => 'actor.destroy', 'uses' => 'ActorController@destroy']);
        get('actor',                    ['as' => 'actor.index',   'uses' => 'ActorController@index']);

        get('employer/create',             ['as' => 'employer.create',  'uses' => 'EmployerController@create']);
        post('employer',                   ['as' => 'employer.store',   'uses' => 'EmployerController@store']);
        get('employer/{username}/edit',    ['as' => 'employer.edit',    'uses' => 'EmployerController@edit']);
        patch('employer/{username}/edit',  ['as' => 'employer.update',  'uses' => 'EmployerController@update']);
        delete('employer/{id}',            ['as' => 'employer.destroy', 'uses' => 'EmployerController@destroy']);
        get('employer',                    ['as' => 'employer.index',   'uses' => 'EmployerController@index']);

        get('ambassador/create',             ['as' => 'ambassador.create',  'uses' => 'AmbassadorController@create']);
        post('ambassador',                   ['as' => 'ambassador.store',   'uses' => 'AmbassadorController@store']);
        get('ambassador/{username}/edit',    ['as' => 'ambassador.edit',    'uses' => 'AmbassadorController@edit']);
        patch('ambassador/{username}/edit',  ['as' => 'ambassador.update',  'uses' => 'AmbassadorController@update']);
        delete('ambassador/{id}',            ['as' => 'ambassador.destroy', 'uses' => 'AmbassadorController@destroy']);
        get('ambassador',                    ['as' => 'ambassador.index',   'uses' => 'AmbassadorController@index']);

        get('lunar/create',             ['as' => 'lunar.create',  'uses' => 'LunarController@create']);
        post('lunar',                   ['as' => 'lunar.store',   'uses' => 'LunarController@store']);
        get('lunar/{username}/edit',    ['as' => 'lunar.edit',    'uses' => 'LunarController@edit']);
        patch('lunar/{username}/edit',  ['as' => 'lunar.update',  'uses' => 'LunarController@update']);
        delete('lunar/{id}',            ['as' => 'lunar.destroy', 'uses' => 'LunarController@destroy']);
        get('lunar',                    ['as' => 'lunar.index',   'uses' => 'LunarController@index']);

    });
    resource('job',             'JobController');
    resource('page',            'PageController');
    resource('sliders',         'SliderController');
    get('/{locale?}',  ['as' => 'admin.dashboard', 'uses' => 'HomeController@index']);
});

get('/confirmDelete/{code}',                ['uses' => 'ProfileController@confirmDelete',              'as' => 'profile.confirmDelete']);

Route::group(['middleware' => ['auth', 'owner']], function() {

    Route::resource('profile', 'ProfileController', ['except' => ['show', 'destroy', 'store', 'index', 'create', 'edit']]);
    // Ajax
    Route::group(['prefix' => 'profile', 'as' => 'profile.'], function() {
        get('{username}/initiateDelete/{locale?}',              ['uses' => 'ProfileController@initiateDelete',            'as' => 'initiateDelete']);

        patch('{username}/ajaxUpdateUser/{locale?}',            ['uses' => 'ProfileController@ajaxUpdateUser',            'as' => 'ajaxUpdateUser']);
        patch('{username}/ajaxUpdateCompany/{locale?}',         ['uses' => 'ProfileController@ajaxUpdateCompany',         'as' => 'ajaxUpdateCompany']);
        patch('{username}/ajaxUpdateCharacteristics/{locale?}', ['uses' => 'ProfileController@ajaxUpdateCharacteristics', 'as' => 'ajaxUpdateCharacteristics']);

        patch('{username}/ajaxUpdateEducation/{locale?}',       ['uses' => 'ProfileController@ajaxUpdateEducation',       'as' => 'ajaxUpdateEducation']);
        post('{username}/ajaxUpdateFiles/{locale?}',            ['uses' => 'ProfileController@ajaxUpdateFiles',           'as' => 'ajaxUpdateFiles']);
        post('{username}/ajaxComplete/{locale?}',               ['uses' => 'ProfileController@ajaxComplete',              'as' => 'ajaxComplete']);

        get('{username}/ajaxNewProject/{locale?}',              ['uses' => 'ProfileController@ajaxNewProject',            'as' => 'ajaxNewProject']);
        get('{username}/ajaxNewWorkshop/{locale?}',             ['uses' => 'ProfileController@ajaxNewWorkshop',           'as' => 'ajaxNewWorkshop']);
        get('{username}/ajaxNewVimeo/{locale?}',                ['uses' => 'ProfileController@ajaxNewVimeo',              'as' => 'ajaxNewVimeo']);
        delete('{username}/removeFromProfile/{locale?}',        ['uses' => 'ProfileController@removeFromProfile',         'as' => 'removeFromProfile']);

        get('{username}/ajaxShowCharasteristics/{locale?}',     ['uses' => 'ProfileController@ajaxShowCharasteristics',   'as' => 'ajaxShowCharasteristics']);
        get('{username}/ajaxShowEducation/{locale?}',           ['uses' => 'ProfileController@ajaxShowEducation',         'as' => 'ajaxShowEducation']);
        get('{username}/ajaxShowFiles/{locale?}',      ['uses' => 'ProfileController@ajaxShowFiles',             'as' => 'ajaxShowFiles']);

        post('{username}/ajaxShowUser/{locale?}',               ['uses' => 'ProfileController@ajaxShowUser',              'as' => 'ajaxShowUser']);
    });
});

resources/views/admin/includes/_crud.blade.php
<div class="crud">
    @if($type == 'user')
        @if($$type->updates)
            <a href="{{ route('profile.preview', [$$type->username, App::getLocale()]) }}" target="_blank" title="{{ trans('messages.approve') }}" class="approve"><i class="fa fa-eye"></i></a>
        @endif
    @elseif($type == 'job')
        @if($$type->updates)
            <a href="{{ route('jobs.preview', [$$type->id, App::getLocale()]) }}" target="_blank" title="{{ trans('messages.approve') }}" class="approve"><i class="fa fa-eye"></i></a>
        @endif
    @elseif ($type == 'ambassador' || $type == 'lunar' || $type == 'page' || $type == 'sliders')
    @else
        @if($$type->user->updates)
            <a href="{{ route('profile.preview', [$$type->user->username, App::getLocale()]) }}" target="_blank" title="{{ trans('messages.approve') }}" class="approve"><i class="fa fa-eye"></i></a>
        @endif
    @endif

    @if ($type == 'ambassador' || $type == 'lunar' || $type == 'sliders')
    @elseif ($type == 'page')
        <a href="{{ route( 'page.show', $slug) }}" title="{{ trans('messages.view') }}" target="_blank" class="view"><i class="fa fa-eye"></i></a>
    @elseif ($type == 'job')
        <a href="{{ route( 'jobs.show', [$id, App::getLocale()]) }}" title="{{ trans('messages.view') }}" target="_blank" class="view"><i class="fa fa-eye"></i></a>
    @else
        <a href="{{ route('profile.show', [isset($username) ? $username : $id, 'locale' => App::getLocale()]) }}" title="{{ trans('messages.view') }}" target="_blank" class="view"><i class="fa fa-eye"></i></a>
    @endif

    @if ($type == 'lunar')
        <a href="{{ route('admin.'.$type.'.edit', [$lunar_id, 'locale' => App::getLocale()]) }}" title="{{ trans('messages.edit_profile') }}" class="edit"><i class="fa fa-pencil-square-o"></i></a>
    @elseif ($type == 'job')
        <a href="{{ route('jobs.edit', [$$type->id, App::getLocale()]) }}" title="{{ trans('messages.edit_job') }}" class="edit"><i class="fa fa-pencil-square-o"></i></a>
    @elseif ($type == 'page')
        <a href="{{ route('admin.'.$type.'.edit', [$page->id, 'locale' => App::getLocale(), 'lang' => $page->code]) }}" title="{{ trans('messages.edit_profile') }}" class="edit"><i class="fa fa-pencil-square-o"></i></a>
    @else
        <a href="{{ route('admin.'.$type.'.edit', [isset($username) ? $username : $id, 'locale' => App::getLocale()]) }}" title="{{ trans('messages.edit_profile') }}" class="edit"><i class="fa fa-pencil-square-o"></i></a>
    @endif

    @if ($type == 'lunar')
        {!! Form::open( ['route' => ['admin.'.$type.'.destroy', $lunar_id], 'method' => 'delete'] ) !!}
    @else
        {!! Form::open( ['route' => ['admin.'.$type.'.destroy', $id], 'method' => 'delete'] ) !!}
    @endif
            {!! Form::button('<i class="fa fa-times"></i>', ['class' => 'btn btn-xs btn-danger', 'type' => 'submit', 'title' => trans('messages.delete')] ) !!}
        {!! Form::close() !!}
</div>

resources/views/admin/includes/box.blade.php
<div class="box box-danger">
    <div class="box-header">
      <h3 class="box-title">{!! $title !!}</h3>
    </div>
    <div class="box-body clearfix">
        {!! $content !!}
    </div>
</div>

resources/views/admin/includes/breadcrumbs.blade.php
{{--<ol class="breadcrumb">--}}
    {{--<li><a href="{{ route('admin.dashboard') }}"><i class="fa fa-dashboard"></i> Home</a></li>--}}
    {{--<li class="active">{{Request::url()}} {{ Route::current()->getName() }}</li>--}}
{{--</ol>--}}

resources/views/admin/includes/footer.blade.php
		<!-- Main Footer -->
		<footer class="main-footer">
		  <!-- To the right -->
		  <div class="pull-right hidden-xs">
		    <strong>Quart CMS</strong>  v 0.0.1
		  </div>
		  <!-- Default to the left --> 
		  <div class="copyright">
		  	<strong>© {{ date('Y') }} Quart Website.</strong> {{ trans('messages.all_rights_reserved') }}. {{ trans('messages.solution_by') }} <a title="web design" target="_blank" href="http://www.quart.ro/">Quart - Creative Agency</a>.
		  </div>
		</footer>


	</div> <!-- ./wrapper -->

	<!-- Scripts -->
	<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.1/js/bootstrap.min.js"></script>

	<script src="{{ asset('/adm/plugins/datatables/jquery.dataTables.js') }}"></script>
	<script src="{{ asset('/adm/plugins/datatables/dataTables.bootstrap.js') }}"></script>
	<script src="{{ asset('/js/bootstrap-multiselect.js') }}"></script>

	<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>

	<script src="{{ asset('/adm/js/jquery/jquery.slimscroll.min.js') }}"></script>
    <script src="{{ asset('/adm/js/AdminLTE.min.js') }}"></script>
	<script src="{{ asset('/js/jquery-ui.min.js') }}"></script>
	<script src="{{ asset('/js/fileinput.min.js') }}"></script>

	@if (App::getLocale() == 'ro')
		<script src="{{ asset('/js/fileinput_locale_ro.js') }}"></script>
	@endif

	<script src="{{ asset('/adm/js/admin.js') }}"></script>

</body>
</html>

resources/views/admin/includes/header.blade.php
<!-- Main Header -->
<header class="main-header">
    <!-- Logo -->
    <a href="{{ route('admin.dashboard', App::getLocale()) }}" class="logo"><b>Quart</b>CMS</a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>

        @if (App::getLocale() == 'ro')
            <a href="{{ route('home') }}" target="_blank" class="topbarLink">{{ trans('messages.view_website') }}</a>
        @else
            <a href="{{ route('page.show', 'en') }}" target="_blank" class="topbarLink">{{ trans('messages.view_website') }}</a>
        @endif

        <ul id="langSelect">
            @foreach ($admin_languages as $lang_code => $lang_uri)
                <li>
                    <a href="{{ $lang_uri }}"
                       @if ($lang_code == App::getLocale()) class="active" @endif
                            >
                        {{ $lang_code }}
                    </a>
                </li>
            @endforeach
        </ul>

      @include('admin.includes.navbarlinks')

    </nav>
</header>

<div class="la-anim-10"></div>

resources/views/admin/includes/mediatab.blade.php
<div role="tabpanel" class="tab-pane" id="media">
    <div class="box box-danger">
        <div class="box-body clearfix whereToUpload" data-route="{{ route('profile.ajaxUpdateFiles', $user->username) }}">
            @include('profile._filesfields')
        </div>
    </div>
</div>

resources/views/admin/includes/projectstab.blade.php
<div role="tabpanel" class="tab-pane" id="projects">
    <div class="box box-danger">
        <div class="box-body clearfix projects editable" data-type="project" data-remove="{{ route('profile.removeFromProfile', $actor->user->username) }}">

            <div class="clearfix">
                <div class="btn btn-success pull-right addToProfile" data-url="{{ route('admin.ajaxNewProject', $actor->user->username) }}">+ {{ trans('messages.new_project') }} </div>
            </div>
            <br/>

            <?php $i = 1; ?>
            @foreach ($actor->user->projects as $key => $project)

                <div class="well project">
                    <div class="btn btn-danger deleteFromProfile" data-id="{{ $project->id }}">-</div>

                    <div class="row">
                        <div class="col-sm-4">
                            <div class="form-group">
                                {!! Form::label('projects[' . $project->id . '][name]', 'Name') !!}
                                {!! Form::text('projects[' . $project->id . '][name]', $project->name , array('placeholder' => 'Name', 'class' => 'form-control')) !!}
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                {!! Form::label('projects[' . $project->id . '][house]', 'Production company / Theatre') !!}
                                {!! Form::text('projects[' . $project->id . '][house]', $project->house , array('placeholder' => 'Production company / Theatre', 'class' => 'form-control')) !!}
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                {!! Form::label('projects[' . $project->id . '][year]', 'Production Year / Season') !!}
                                {!! Form::text('projects[' . $project->id . '][year]', $project->year , array('placeholder' => 'Production Year / Season', 'class' => 'form-control')) !!}
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-4">
                            <div class="form-group">
                                {!! Form::label('projects[' . $project->id . '][director]', 'Director') !!}
                                {!! Form::text('projects[' . $project->id . '][director]', $project->director , array('placeholder' => 'Director', 'class' => 'form-control')) !!}
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                {!! Form::label('projects[' . $project->id . '][role]', 'Role') !!}
                                {!! Form::text('projects[' . $project->id . '][role]', $project->role , array('placeholder' => 'Role', 'class' => 'form-control')) !!}
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                {!! Form::label('projects[' . $project->id . '][description]', 'Description') !!}
                                {!! Form::textarea('projects[' . $project->id . '][description]', $project->description , array('placeholder' => 'Description', 'class' => 'form-control', 'rows' => 3)) !!}
                            </div>
                        </div>
                    </div>
                </div>

                <hr/>

            @endforeach

        </div>
    </div>
</div>

resources/views/admin/includes/sidebar.blade.php
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">

<!-- sidebar: style can be found in sidebar.less -->
<section class="sidebar">

  <!-- Sidebar user panel (optional) -->
  <div class="user-panel">
    <div class="pull-left image">
      <img src="{{ asset('adm/dist/img/user2-160x160.jpg')  }}" class="img-circle" alt="User Image" />
    </div>
    <div class="pull-left info">
      <p>{{ $logged->fname . ' ' . $logged->lname }}</p>
      <!-- Status -->
      {{--<a href="#"><i class="fa fa-circle text-success"></i> Online</a>--}}
    </div>
  </div>

  <!-- search form (Optional) -->
  {{--<form action="#" method="get" class="sidebar-form">--}}
    {{--<div class="input-group">--}}
      {{--<input type="text" name="q" class="form-control" placeholder="Search..."/>--}}
      {{--<span class="input-group-btn">--}}
        {{--<button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>--}}
      {{--</span>--}}
    {{--</div>--}}
  {{--</form>--}}
  <!-- /.search form -->

  <!-- Sidebar Menu -->
  <ul class="sidebar-menu">
    <li>
        <a href="{{ route('admin.dashboard', ['locale' => App::getLocale()]) }}"><i class="fa fa-dashboard fa-fw"></i>{{ trans('messages.go_to_dashboard') }}</a>
    </li>
    <li class="treeview">
        <a href="{{ route('admin.user.index', ['locale' => App::getLocale()]) }}">
          <i class="fa fa-users"></i><span>{{ trans('messages.users') }}</span> <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
          <li><a href="{{ route('admin.user.create', ['locale' => App::getLocale()]) }}"><i class="fa fa-circle-o"></i>{{ trans('messages.add_new') }}</a></li>
          <li><a href="{{ route('admin.user.needapprove', ['locale' => App::getLocale()]) }}"><i class="fa fa-circle-o"></i>{{ trans('messages.approve') }}</a></li>
          <li><a href="{{ route('admin.user.index', ['locale' => App::getLocale()]) }}"><i class="fa fa-circle-o"></i>{{ trans('messages.all_users') }}</a></li>
        </ul>
    </li>
    <li class="treeview">
        <a href="{{ route('admin.actor.index', ['locale' => App::getLocale()]) }}">
          <i class="fa fa-smile-o"></i><span>{{ trans('messages.actors') }}</span> <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
          {{--<li><a href="{{ route('admin.actor.creat[e',, localelang' => App::getLocale()) })]"><i class="fa fa-circle-o"></i>{{ trans('messages.add_new') }}</a></li>--}}
          <li><a href="{{ route('admin.actor.needapprove', ['locale' => App::getLocale()]) }}"><i class="fa fa-circle-o"></i>{{ trans('messages.approve') }}</a></li>
          <li><a href="{{ route('admin.actor.index', ['locale' => App::getLocale()]) }}"><i class="fa fa-circle-o"></i>{{ trans('messages.all_actors') }}</a></li>
        </ul>
    </li>
    <li class="treeview">
        <a href="{{ route('admin.employer.index', ['locale' => App::getLocale()]) }}">
          <i class="fa fa-building"></i><span>{{ trans('messages.employers') }}</span> <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
          {{--<li><a href="{{ route('admin.employer.creat[e',, localelang' => App::getLocale()) })]"><i class="fa fa-circle-o"></i>{{ trans('messages.add_new') }}</a></li>--}}
          <li><a href="{{ route('admin.employer.needapprove', ['locale' => App::getLocale()]) }}"><i class="fa fa-circle-o"></i>{{ trans('messages.approve') }}</a></li>
          <li><a href="{{ route('admin.employer.index', ['locale' => App::getLocale()]) }}"><i class="fa fa-circle-o"></i>{{ trans('messages.all_employers') }}</a></li>
        </ul>
    </li>
    <li class="treeview">
        <a href="{{ route('admin.ambassador.index', ['locale' => App::getLocale()]) }}">
            <i class="fa fa-users"></i><span>{{ trans('messages.ambassadors') }}</span> <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
            <li><a href="{{ route('admin.ambassador.create', ['locale' => App::getLocale()]) }}"><i class="fa fa-circle-o"></i>{{ trans('messages.add_new') }}</a></li>
            <li><a href="{{ route('admin.ambassador.index', ['locale' => App::getLocale()]) }}"><i class="fa fa-circle-o"></i>{{ trans('messages.all_ambassadors') }}</a></li>
        </ul>
    </li>
    <li class="treeview">
        <a href="{{ route('admin.lunar.index', ['locale' => App::getLocale()]) }}">
            <i class="fa fa-users"></i><span>{{ trans('messages.actor_month') }}</span> <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
            <li><a href="{{ route('admin.lunar.create', ['locale' => App::getLocale()]) }}"><i class="fa fa-circle-o"></i>{{ trans('messages.add_new') }}</a></li>
            <li><a href="{{ route('admin.lunar.index', ['locale' => App::getLocale()]) }}"><i class="fa fa-circle-o"></i>{{ trans('messages.all_actors_month') }}</a></li>
        </ul>
    </li>
    <li class="treeview">
        <a href="{{ route('admin.job.index', ['locale' => App::getLocale()]) }}">
            <i class="fa fa-users"></i><span>{{ trans('messages.jobs') }}</span> <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
            <li><a href="{{ route('admin.job.needapprove', ['locale' => App::getLocale()]) }}"><i class="fa fa-circle-o"></i>{{ trans('messages.approve') }}</a></li>
            <li><a href="{{ route('admin.job.index', ['locale' => App::getLocale()]) }}"><i class="fa fa-circle-o"></i>{{ trans('messages.all_jobs') }}</a></li>
        </ul>
    </li>
    <li class="treeview">
        <a href="{{ route('admin.page.index', ['locale' => App::getLocale()]) }}">
            <i class="fa fa-users"></i><span>{{ trans('messages.pages') }}</span> <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
            <li><a href="{{ route('admin.page.create', ['locale' => App::getLocale()]) }}"><i class="fa fa-circle-o"></i>{{ trans('messages.add_new') }}</a></li>
            <li><a href="{{ route('admin.page.index', ['locale' => App::getLocale()]) }}"><i class="fa fa-circle-o"></i>{{ trans('messages.all_pages') }}</a></li>
        </ul>
    </li>
    <li class="treeview">
        <a href="{{ route('admin.sliders.index', ['locale' => App::getLocale()]) }}">
            <i class="fa fa-users"></i><span>{{ trans('messages.sliders') }}</span> <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
            <li><a href="{{ route('admin.sliders.create', ['locale' => App::getLocale()]) }}"><i class="fa fa-circle-o"></i>{{ trans('messages.add_new') }}</a></li>
            <li><a href="{{ route('admin.sliders.index', ['locale' => App::getLocale()]) }}"><i class="fa fa-circle-o"></i>{{ trans('messages.all_sliders') }}</a></li>
        </ul>
    </li>
    <!-- Optionally, you can add icons to the links -->
    {{-- <li class="active"><a href="#"><span>Link</span></a><</li> --}}
  </ul>
</section>
<!-- /.sidebar -->
</aside>